### ISSUE TITLE
Ensure only one TaskRecord exists for each version.

### ISSUE THREAD

**Issue by crazydog115** [theSteveMitchell/after_party#18]
Manually re-running a task can create duplicate `TaskRecord`s.

I believe that if a task is being re-run, it shouldn't actually create the record.

**Comment by theSteveMitchell** [comment]
Task Records were originally built around the analogy of "data migrations", as a counterpart to schema_migrations.  And, since schema_migrations in rails can only be run once, that's how after_party tasks currently work.

I recognize the need to run tasks more than once, but my solution would be to add a pk to task_records (and probably a date) so you can re-run as much as you like, but still go and reference the times it was run.

So, I think I'm going to close this since it's already covered in #7
