### ISSUE TITLE
Post-Install message

### ISSUE THREAD

**Issue by schmijos** [theSteveMitchell/after_party#63]
Isn't it a pity that this gem after installation doesn't say: "When you after_party, you must party hard!"

**Comment by theSteveMitchell** [comment]
😆 @schmijos I agree, it's a missed opportunity. But, HTTParty [already did that](https://github.com/jnunemaker/httparty/commit/e221365029395897e8c6ca9a3a372ae0de3c4888)...in 2008. And, I have to admit this may have inspired After_party when I wrote it in 2013. 

With Apologies to @jnunemaker, I think that code (the install message itself) was poorly written. The following several paragraphs explain my reasoning.

The original quote references the song "Party Hard" by Andrew Wilkes-Krier (Andrew W.K.) released in 2001. If you grew up watching MTV in the early aughts, you would have seen this music video and broken into a dance right away. The lyrics include these lines:

"Now it's time to party, and we'll party hard"
"When it's time to party, we will always party hard"
and 
"Party Hard! Party Hard!" (repeat 12x)

Most people would remember that the song also includes the phrase "When it's time to party, you must always party Hard!" However, "you must party hard" never appears in the song. The word "must" never appears in the song. I believe this to be a Mandela Effect thing, since probably most people remember the lyric as "you must party hard". Is this proof that our universe somehow switched timelines after 9-11? Yes, obviously.

The lyrics are meant as an invitation to JOIN US in our hard-partying, never as an instruction or an obligation that YOU need to start your own party. 

Now, in the case of HTTParty, the post install message is "When you HTTParty, you must party hard!" In my humble opinion, this is a miss for three fatal reasons:
1. There is a syllable mismatch. HttpParty's version has 12 syllables, Vs. the 11 or the 13 in the two lines of Andrew W.K.'s song. 
2. While the naming of HttParty is very clever, it's a mouthful to say in this lyric. In my P.h.D. dissertation, I survey 5 developers, and all five diminish the syllable for the second T. They pronounce it as four syllables "H T(t) party)" or you could think of it as a four-syllable word "H T Party" but with just a micro-stutter on the T. No one in my research pronounces it as a full five syllable "H T T Party". So developers end up saying in their heads "When you H T Party, you must party hard!", which does restore the original 11 syllables to match the song lyric and cadence, but now you have developers celebrating something called "HTParty" instead of "HTTParty"
3. Inverting the action and consequence. You install HTTParty, and upon completing the installation, you learn that in order to use the gem, it's necessary to party hard. I now have an obligation to party hard, as a result of installing the gem? Thanks for that. In Contrast, I would prefer to invite developers to the existing party, and to let them know that they are invited to party, or closer to the party, as a result of installing the gem. 

So, @schmijos, the version you proposed does fit the syllable requirement, and also the right cadence. But, suffers from the inverted action/consequence as I explained. If we were to add a post-install message to After_party, it would be more like:
"Now it's time to party, After_Party hard!". I think this is the closest we can get to the original song lyric, we're only replacing the two syllables "And we'll" with "Af-ter". It helps the installer to know that, we brought the party to them. They've just installed the party, we brought it to them, and they're now invited, not obligated". But, I think since HttParty already did it, and the community would see it as plagiarism, I don't think it's appropriate to add the post-install message.

I'll keep this open for a few years for comments
