### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by gmontard** [theSteveMitchell/after_party#8]
In the documentation you tell to use this command for an asynchronous running of the command:
```
   run "cd #{release_path} ; nohup #{rake} after_party:run RAILS_ENV=#{rails_env} > #{current_path}/log/after_party.log  2>&1 &", :pty => false
```

In fact you don't need the **&** at the end because you already use **nohup** command, it even makes it not working for me, so this command is sufficient:
```
   run "cd #{release_path} ; nohup #{rake} after_party:run RAILS_ENV=#{rails_env} > #{current_path}/log/after_party.log  2>&1", :pty => false
```

**Comment by theSteveMitchell** [comment]
Hi @gmontard sorry for extremely late reply.  For me, The command doesn't work as expected when I drop the **&**.  I wonder if this could be caused by a different in platform version or capistrano/ruby.

I tested with a job that looked like this:
```ruby
namespace :after_party do
  task :debug_deploy_thing => :environment do
    Dir[Rails.root.join("lib/after_party/*.rb")].each {|f| require f}
    20.times do |i|
      puts i
      sleep(1)
    end
  end
end
```

I ran my `cap deploy:after_party` task while also tailing the logs in a terminal on the server.  
When I use **&** the cap terminal returns immediately from the rake command, and exits.  When I omit the **&** that rake task the cap terminal is blocked until after_party finishes (~20 seconds).  

Can you describe what you were seeing?
